---
title: "Introduction to Accounting"
output: beamer_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Goals

+ Enough background so non-accountants have some idea of what accountants do.
+ A shared language of terms for when we work together.
+ Appreciation that we all have our parts
    + Engineers tend to stick with cost estimation
    + Economists tend to stick with revenue estimation
    + Accounting types often do the rest with a focus on tax
+ Set you up for cash flow forecasts later in the course.
    + Frequent job activity
    + Also needed for business loans and business plans
    
Enough knowledge to read the basic documents but not enough to create them.

## Warnings

+ Will feel like drinking from firehouse if you have no background but same pace as intro accounting.
+ Shortcuts/simplifications to get set up for cash flow forecasts.
    + Barrier between income statement and balance sheet. Revenue and expenses not immediately reflected.
    + Forget about contra accounts.
    + Simplification of the connection between balance sheet and cash flow statement.
        + All asset purchases, even inventory, are cash from investments.
        + All borrowing and lending, even accounts receivable/payable, are cash from finance.
    
## Focus on Financial Accounting

+ Financial accounting focuses on the preparation of documents for public consumption.
    + Balance sheet (Assets, Liabilities and Owner Equity)
    + Income statement (Revenue and Expenses)
    + Cash Flow statement (Inflows and Outflows of Cash)
+ There are other accounting areas
    + Audit (Makes sure people follow the rules and are not misstating things.)
    + Cost or Managerial (Cost benefit, volume studies, accounting approach to much of this class.)
    + Forensic (Get an attorney)
    + Fund and Governmental (Where money is separated and has strings)
    + Tax (Often Different Rules)

## What is in the three documents?

This is mostly a discussion of nouns.  We will add verbs and get *transactions* later.

https://prezi.com/agobxmlocjgj/accountingnoquiz/

## In summary

+ Balance Sheet
    + Assets, things that can be owned.
        + Current, things that turn into cash over the normal course of doing business.
        + Fixed, things that require an act of volition to turn into cash.
        + Other
    + Liabilities, things that are owed
        + Current, requires cash in the near future
        + Other
    + Owner equity, what is left over OE $\equiv$ Assets - Liabilities
+ Income statement, revenue and expenses
    + More expenses increase a positive number
    
## Summary (Con't)

+ Cash Flow Statement, More cash = increase
    + Operations
        + Same direction as net income
    + Investments
        + Increase if you sell and asset.
    + Finance
        + Increase if you borrow
        + Increase with new owners _investing_

## For Next Class

Bring an income statement, cash flow statement, and balance sheet for any firm you like.

+ Not Nike or Intel (Or half the class will bring these)
+ Avoid banks (Balance sheets look funny)
+ Avoid non-us firms (Different sign conventions)

Bring means, paper or provide a link when asked.

## Where to Get The Statments

+ https://finance.yahoo.com/
+ http://www.google.com/finance

+ https://www.sec.gov/edgar/searchedgar/companysearch.html

Or  go to the company webpages and look for investor relations.

## Quiz!

https://prezi.com/rukunfcbnemy/intro-accounting/

## Connections between the documents

+ Think about the cash flow statement as the consequences of balance sheet and net income changes.
+ Things that change net income changes cash from operations
+ Asset purchases and sales change cash from investments.
+ Borrowing, lending and owner equity changes are reflected in cash from finance.

## How to Drill and Kill the transactions

+ Resources 
    + Wiki page http://ec314-pdx-edu.wikidot.com/q1:accounting
    + There are a small number of transactions I ask about.  Thirteen are listed but there are really only eight.
    + Bottom of the page has a link to past examples (https://drive.google.com/drive/u/0/folders/0B3ilawp4z7olelZTWE5lNHJIV0E)
    + And videos of my explaining things (https://www.youtube.com/playlist?p=PL9B50CBC168EDAFC7)

+ Learn the transactions first.  Flash cards work well.
+ Then practice on categorizing actual transactions into the 8 that you know. Use the videos and past examples for this


## Flashcards

One side has a transaction like "Buy an asset"

The reverse has something like this.


\begin{center}
\begin{tabular}{|p{.75 in} |p{.75 in}|  p{.75 in}|}
\hline 
Rev  & Assets & Operations \\
&$\uparrow \downarrow$ &\\
&&\\
\hline
Expense & Liabilities & Investments\\
&&$\downarrow$\\
&&\\
\hline
 & OE & Finance\\
&&\\
&&\\
\hline
\end{tabular}
\end{center}


## Example Take Out a Loan

\begin{center}
\begin{tabular}{|p{.75 in} |p{.75 in}|  p{.75 in}|}
\hline 
Rev  & Assets & Operations \\
&$\uparrow$ &\\
&&\\
\hline
Expense & Liabilities & Investments\\
&$\uparrow$&\\
&&\\
\hline
 & OE & Finance\\
&&$\uparrow$\\
&&\\
\hline
\end{tabular}
\end{center}


## Example Revenue increase

\begin{center}
\begin{tabular}{|p{.75 in} |p{.75 in}|  p{.75 in}|}
\hline 
Rev  & Assets & Operations \\
$\uparrow$& &$\uparrow$\\
&&\\
\hline
Expense & Liabilities & Investments\\
&&\\
&&\\
\hline
 & OE & Finance\\
&&\\
&&\\
\hline
\end{tabular}
\end{center}

## Lets Try an Example

This is before Biketown came into existence.

https://drive.google.com/file/d/0B3ilawp4z7olcVl5TXQ5dVI0WFU/view

## Back to the Pre-test

+ Which of the following is _not_ an asset?
    + Employees 
    + Land
    + Machinery
    + Cash
    + Owner Equity
    + Accounts Receivable



+ Which of the following is a liability?
    + Cash
    + Accounts Receivable
    + Owner Equity
    + Tax Owed
    + None of the above


+ Which of the following is an expense?
    + Owner Equity
    + A Loan
    + Taxes
    + None of the above


