---
title: "Syllabus EC314 Winter 2017"
author: "James Woods"
date: ""
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Course Description

This course will examine the tools required to analyze expenditures that yield benefits over time -- investments. The use of accounting documents and a focus on the time value of money will allow students to analyze choices in a variety of security, loan, and equipment investment decisions. The main objectives are to prepare engineers for their PE and FE exams and to provide engineers, economists and others with a shared language and understanding of basic finance topics.

## Prerequisites

There are no prerequisites for this course. However, a reasonable math
background, MTH 95, is a practical requirement. 

A brief assessment that includes math skills from MTH 70 and 95 will be given on the first day.  If you don't do well on that part of the assessment, you should reconsider enrolling in this course.


## Key Dates

+ Final Exam: March 23rd, 8 am
+ Midterm 1: February 2nd
+ Midterm 2: February 23rd
+ Last day to drop or change grade option: February 26th.

Exams will be given on those days and at those times only.  I do not give make up, early or late exams.  

If you have a DRC compensation and would normally schedule an exam in the testing center, you must schedule your exam on the day of the exam and start at the same time as the rest of the class.

# Contact Information

Communication will be handled through slack https://ec314winter17.slack.com. You should have received an invitation, if not, just go to that URL and use your @pdx.edu email to sign up. There are reasonable help documents to get you started. https://get.slack.help/hc/en-us/articles/218080037-Getting-started-for-new-users

Slack will be used for IM, email and forum style communication.  It even handles phone calls. If you have a question about course material or the course itself, ask in one of the channels. If you have a personal message that is not intended for others, send a direct message. The group has global do not disturb hours of 10pm -8am.  If you would like something different, alter your personal settings.

Please note that I am not online all the time, and when I am online I will prioritize well-phrased questions with sufficient detail.  I tend to ignore general complaints, questions that can be answered by reading the syllabus or using the search bar.  

I will not react to questions in the two days prior to an exam  under most circumstances. I am just trying to protect my workload from student procrastination.  *If your study strategy is to cram the night before, you are on your own.* 


Office Hours:

+ My office is in CH 241-O.
+ Drop in office hours are Tuesday 1:00-2:30pm  through the last week of class. There is no need to make an appointment for these hours -- just come.
+ If you can’t attend regular office hours, please check my calendar https://woodsj.youcanbook.me/. I will make a limited number of 20 minute slots available each week. If you make an appointment and fail to show up without first canceling, I will penalize your final exam score two points.  

Office hours for Kevin Payne, the teaching assistant,  will be posted on slack after the first week of class.  We will also post some hours where we will available interactively on slack.

# Textbook and Other Resources

Most engineering economics texts have just about the same material, with some small variations and additions. I have assigned Chan S. Park ``Contemporary Engineering Economics
6ed'' as a convenience to students that have their textbooks paid for by a third party. It contains enough of the accounting material that is normally not included in an engineering economics course, but is included in this one to make it part of a universities studies cluster course. 


I am pretty comfortable with any engineering economics textbook you choose, but it is your responsibility to figure
out the relevant readings from the descriptions of the subject matter.
The table of contents for the 6th edition (https://s3-us-west-2.amazonaws.com/woodsjteaching/TableOfContents6thEd.pdf) is posted to help you
make the correspondences.  Many students have found the textbook unnecessary given the online resources.  The goal is to have your textbook cost less than $30.

``Schaum's Outline of Engineering Economics'' by Sepulveda, Souder and Gottfried is a useful second reference if you are having trouble with time value of money.

## Online Resources
We will make significant use of online resources and technology.  The
two main tools are:

+ D2L
+ Course Wiki

### Netiquette
Since we will be having some online interaction, we should be clear
about what we should and should not do.

In class, I can see what is going on at all times.  In the online
environment, I can't see everything and I can't react as quickly to
what I do see.  Students are expected to be particularly trustworthy
both in terms of their own conduct, and in reporting inappropriate
conduct to me.

I will not tolerate profanity, obscenity, or remarks intended to
discount or dismiss either a person or his or her point of view. If your inappropriate message is in the public forum, I will warn you
once in that public space. If you continue with inappropriate conduct
in the public spaces, your access to them will be denied for the rest
of the term. If your inappropriate conduct is in private, a student code of conduct violation complaint may be filed. 
 
### D2L

D2L is our main platform for for practice quizzes and the outline of course material.  Should you have technical problems with D2L
or your computer please resolve them yourself with the general campus
help desk or D2L help (http://www.pdx.edu/oit/d2l).  You will
also find a tutorial on how to use D2L on your D2L landing page.
*You are responsible for learning how to use D2L.*

The course D2L landing page will have several important links:

  + EC314 Wiki, where most of the supplementary material, videos and
    podcasts reside.
  + Schedule an Appointment, where you can arrange times to meet
    other than office hours for help.
  + Calendar of Topics and Deadlines, for deadlines and due dates.
  + Table of Contents for 6th Edition Book

Pay particular attention to the course content tab in the upper
left. This is where most of the online work starts.  Each module will
be structured with one or more of the following:

  + Textbook sections to read
  + Wiki pages to review
  + One or more practice quizzes

The practice quizzes are not timed and will be slightly different each time you take them. Because they are auto-graded, they are not as sophisticated or nuanced as the exam questions.


### Course Wiki

The second most important resource is the wiki.  Most of the
supplementary reading material, videos, screencasts, and podcasts are
collected here. You should visit the ``Course Outline'' link on the
left http://ec314-pdx-edu.wikidot.com/outline to see what we will be doing.

A link to the wiki may be found on the D2L landing page.  You must create both a wikidot account and ask for access to the course wiki.  Create the account first, log in, and ask for access by filling out the request form.  I log in once a day and allow everyone access.  

An account is required so that it is easy for you to make corrections to the wiki.  _If you see something that needs fixing -- fix it._  If it is wrong, we can roll it back.  Don't be shy about making edits.  There are ``how to'' pages and sandbox to help you out.

This resource is outside of PSU and the help desk will not provide
assistance.  You and I are both customers. I have no special status.


# Assessments and Grade Policy

Your grade in the class will be based on your performance on the midterms and the final exam.  

+ Final Exam (40%)
+ Midterm 1 (30%)
+ Midterm 2 (30%)

The quizzes in D2L are not part of your grade, but you will be hard pressed to pass the class without spending significant time with the material.

Course grades will be based on class rank with cut points between letter grades determined by gaps in the distribution.  

## In-class Exams

D2L has samples of exams to get you familiar with the style of the questions. The keys will have a few errors, but the errors are frequently noted in the errata page.

Students will be assigned seats and photo ID will be required for all exams. You will only be allowed a writing implement and a calculator.  No headphones, phones, smart watches, internet connected devices, or other material will be allowed.  All backpacks will be stored at the front or side of the classroom.  If we see a phone, we will take your exam, you will receive a zero, and you will be sent to the dean of student life.


## Practice D2L Quizzes

D2L quizzes are not included in the grade calculation.  They are all multiple choice and calculation style questions and intended as one way, but not the only way to practice for the exams.

# Topics

Course topics were developed based on the need for students to pass the PE and FE exams, my own experience as a consultant, as well as the restrictions imposed by this class being a university studies, U, course.  Full details on the topics, including textbook readings, references to the course wiki, and quizzes are in D2L.  A rough outline is below:

+ Accounting

    + Introducation to accounting concepts
    + Accounting ratios

+ Time value of money

    + Notation and Calculations
    + Loans

+ Investment Criteria

    + Present Worth
    + Annual Worth
    + Internal Rate of Return
    
+ Cost Estimation

    + Depreciation and Taxes
    + Cash flow projections

+ New Environments
    
    + Increasing cost of funds
    + Capital Budgeting

+ Single Period Choice

    + Cost functions
    + Break-even
    + Make vs Buy
    + Optimal pace
    
+ Uncertainty
    
    + Sensitivity Analysis
    + Belief Elicitation
    + Monte Carlo simulations


# Other Rules

+ Begging for grades will result in an immediate lowering of your course grade by a full letter grade.
  
<!-- + When completing online quizzes you may use your book, wiki, calculator, spreadsheets, notes, or other resources as long as it is not another student or person.  *The work must be authentically and genuinely your own. In other words, if you are copying answers you found online, it is not your work.* -->

+ Go to office hours at the first sign of trouble -- not as a last resort.

+ In this classroom, we support and value diversity.  To do so requires that we:

    + Respect the dignity and essential worth of all individuals
    + Promote a culture of respect toward all individuals
    + Respect the privacy, property, and freedom of others
    + Reject bigotry, discrimination, violence, or intimidation of any kind
    + Practice personal and academic integrity and expect it from others
    + Promote the diversity of opinions, ideas, and backgrounds, which is the lifeblood of a university

   For additional information, please see the Office of Affirmative Action \& Equal Opportunity at http://www.pdx.edu/diversity/affirmative-action.


+ Accommodations are collaborative efforts between students, faculty, and the Disability Resource Center.  If you have a documented disability and require accommodation, you must arrange to meet with the course instructor prior to or within the first week of the term.  The documentation of your disability must come in writing from the Disability Resource Center (Faculty letter).  Students who believe they are eligible for accommodations but who have not yet obtained approval through the DRC should contact the DRC immediately.  Reasonable and appropriate accommodations will be provided for students with documented disabilities.  For more information on the Disability Resource Center, please see http://www.drc.pdx.edu/. 

+ Academic honesty is expected and required of students enrolled in this course.  Suspected academic dishonesty in this course will be handled according to the procedures set out in the Student Code of Conduct.

+ I am sympathetic to family emergencies but you must inform me as soon as possible. If the notice is verbal, please email me with your understanding of our agreement. All agreements have to be in writing.

+ This course meets degree requirements in several ways:
    + The “U” in the course number indicates that this course belongs to a University Studies Upper-Division Cluster, so you may be here to earn cluster credit;
    + This course is an elective for the economic, BSQE, and other majors, so you may be here to earn credit towards your major;
    + This course serves as an elective in several economics minors, so you may be here to earn credits towards your minor;
    + Since you can double-dip your Cluster credits and credits towards a minor, you may be here to earn both Cluster and minor credit. 

+ This course is part of the following cluster(s): Design Thinking/Innovation/ Entrepreneurship; Knowledge, Values, and Rationality; Community Studies.

Link to this syllabus https://github.com/woodsjam/PSU-EC314.  There is a branch for each term.  Be sure to choose the correct branch to see the current syllabus.  
