---
title: "Pre-Test"
author: "James Woods"
date: "12/28/2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Directions

This is just a pre-test to see where everyone is on math, accounting and finance topics.  It does not count for a grade; I just need the information to guide a few lectures.

## Math

1. Add $$\frac{2}{x+3} + \frac{5}{x+2}$$

$$\frac{2}{x+3} + \frac{5}{x+2} = \frac{2(x+2)}{(x+2)(x+3)} + \frac{5 (x+3)}{(x+2)(x+3)} \\ = \frac{7x + 19}{(x+2)(x+3)}$$

2. Use the properties of exponents to simplify this expression: $$\frac{14(x^2 y^3)^2}{7 x^3 y^{10}}$$

$$\frac{14(x^2 y^3)^2}{7 x^3 y^{10}} =  \frac{14(x^4 y^6)}{7 x^3 y^{10}} = \frac{2 x}{y^4}$$

3. Set up and solve a system of equations to answer this question.  A theater sells adult tickets for \$8 and children’s tickets for \$5.  If a total of $236 was taken in on sales of 34 total tickets, how many adult tickets and how many children’s tickets were sold?

Set up as:
$$ A + C = 34$$ 
$$8 A + 5 C = 236 $$

Substitute in:
$$A = 34-C $$
$$8 (34-C) + 5 C = 236$$
$$272 - 8C + 5 C = 236$$
$$-3 C = -36 $$
$$C = 12 $$
$$A = 34 - C = 34 - 12 = 22$$


## Accounting Concepts

1. Which of the following is _not_ an asset?
    + Employees 
    + Land
    + Machinery
    + Cash
    + Owner Equity
    + Accounts Receivable

Employees are expenses, not assets.  You can't own them, so they can't be an asset.  

Land, Machinery and Cash are all assets since they can be owned.

Owner equity is not an asset, it is what is left over after subtracting liabilities from assets.  

Accounts receivable is an asset.  Those are invoices that you have sent out but have not been paid yet.


2. Which of the following is a liability?
    + Cash
    + Accounts Receivable
    + Owner Equity
    + Tax Owed
    + None of the above

Cash and Accounts Receivable are both assets, and owner equity is just the difference between assets and liabilities.

"Tax Owed" is a colloquialism for a few accounting terms.  "Tax Owed" is a liability if you visualized is as a fixed amount sitting on the balance sheet.  It is an expense if you visualized it as an amount per month.

3. Which of the following is an expense?
    + Owner Equity
    + A Loan
    + Taxes
    + None of the above

As discussed above, Owner Equity is the difference between assets and liabilities and not an expense.  

The loan is a liability, but the payment you make is partially an expense, the interest part, and partly just an outflow of cash.

Taxes are the expense.  Usually, when you see it like this it is intended to be a flow and would show up on the income statement as an expense.

## Interest

1.  Suppose you deposit \$100 into an account that earns 12% a year compounded _annually_.  How much would be in the account after 10 years?

$$ 100 (1+.12)^{10} = `r 100*1.12^10`$$

2.  Suppose you deposit \$100 into an account that earns 12% a year compounded _monthly_.  How much would be in the account after 10 years?

$$ 100 (1+.01)^{120} = `r 100*1.01^120`$$

## Choice

Consider the following assets:

Year| A | B | C
----|---|---|---
0   | 0 | 0 |0
1   |10 |0  |0
2   |0  |10 |20 

Asset A gives \$10 in year 1.  Asset B gives \$10 in year 2 and asset C gives \$20 in year 2.

1. Between A and B, which would you prefer and why?

Both A and B give you the same amount but A gets the money to you sooner, so you prefer A.

2. Between B and C, which would you prefer and why?

Both B and C give you benefits in year 2 but C gives you more, so you prefer C.

3. Between A and C, which would you prefer and why?

It depends.  There are times when you prefer A or C.  It depends on the interest rate.  If the interest rate is high, 100% or greater, you will prefer A.  We will do these comparisons in class.

